regular_cws_songs = {
    "CWS_130": {"artist": "Aerosmith", "song": "Walk This Way"},
    "CWS_169": {"artist": "White Zombie", "song": "Thunder Kiss '65"},
    "CWS_170": {"artist": "Alice Cooper", "song": "No More Mr. Nice Guy"},
    "CWS_171": {"artist": "Alice in Chains", "song": "Stone"},
    "CWS_172": {"artist": "Arctic Monkeys", "song": "R U Mine?"},
    "CWS_173": {"artist": "Avenged Sevenfold", "song": "Bat Country"},
    "CWS_174": {"artist": "Bob Dylan", "song": "Knockin' on Heaven's Door"},
    "CWS_175": {"artist": "Boston", "song": "Peace of Mind"},
    "CWS_176": {"artist": "Bush", "song": "Machinehead"},
    "CWS_177": {"artist": "B'z", "song": "Ultra Soul"},
    "CWS_178": {"artist": "Def Leppard", "song": "Pour Some Sugar on Me (2012)"},
    "CWS_179": {"artist": "Deftones", "song": "My Own Summer (Shove It)"},
    "CWS_180": {"artist": "EarlyRise", "song": "Wasteland"},
    "CWS_181": {"artist": "Fang Island", "song": "Chompers"},
    "CWS_182": {"artist": "Foo Fighters", "song": "Everlong"},
    "CWS_183": {"artist": "Gold Motel", "song": "Brand New Kind of Blue"},
    "CWS_184": {"artist": "Green Day", "song": "X-Kid"},
    "CWS_185": {"artist": "Iron Maiden", "song": "The Trooper"},
    "CWS_186": {"artist": "Jack White", "song": "Sixteen Saltines"},
    "CWS_187": {"artist": "Jaws", "song": "Stay In"},
    "CWS_188": {"artist": "Joe Satriani", "song": "Satch Boogie"},
    "CWS_189": {"artist": "Kiss", "song": "Rock and Roll All Nite"},
    "CWS_190": {"artist": "La Sera", "song": "Love That's Gone"},
    "CWS_191": {"artist": "Magic Wands", "song": "Black Magic"},
    "CWS_192": {"artist": "Mastodon", "song": "Blood and Thunder"},
    "CWS_193": {"artist": "Minus the Bear", "song": "Cold Company"},
    "CWS_194": {"artist": "Monster Truck", "song": "Sweet Mountain River"},
    "CWS_195": {"artist": "Muse", "song": "Knights of Cydonia"},
    "CWS_196": {"artist": "Nirvana", "song": "Heart Shaped Box"},
    "CWS_197": {"artist": "Oasis", "song": "Don't Look Back in Anger"},
    "CWS_198": {"artist": "Pantera", "song": "Cemetery Gates"},
    "CWS_199": {"artist": "Paramore", "song": "Now"},
    "CWS_200": {"artist": "Paws", "song": "Sore Tummy"},
    "CWS_201": {"artist": "Queen", "song": "We Are the Champions"},
    "CWS_202": {"artist": "Radiohead", "song": "Paranoid Android"},
    "CWS_203": {"artist": "Ramones", "song": "Blitzkrieg Bop"},
    "CWS_204": {"artist": "Ratt", "song": "Round and Round"},
    "CWS_205": {"artist": "Red Fang", "song": "Wires"},
    "CWS_206": {"artist": "R.E.M.", "song": "Losing My Religion"},
    "CWS_207": {"artist": "Rise Against", "song": "Savior"},
    "CWS_208": {"artist": "Rush", "song": "The Spirit of Radio"},
    "CWS_209": {"artist": "Screaming Females", "song": "Rotten Apple"},
    "CWS_210": {"artist": "Slayer", "song": "War Ensemble"},
    "CWS_211": {"artist": "Splashh", "song": "All I Wanna Do"},
    "CWS_212": {"artist": "System of a Down", "song": "Hypnotize"},
    "CWS_213": {"artist": "Tak Matsumoto", "song": "Go Further"},
    "CWS_214": {"artist": "The Dear Hunter", "song": "Stuck on a Wire Out on a Fence"},
    "CWS_215": {"artist": "The Kinks", "song": "You Really Got Me"},
    "CWS_216": {"artist": "The Police", "song": "Every Breath You Take"},
    "CWS_217": {"artist": "The Rolling Stones", "song": "Paint It Black"},
    "CWS_218": {"artist": "The Shins", "song": "For a Fool"},
    "CWS_219": {"artist": "The Smashing Pumpkins", "song": "The Chimera"},
    "CWS_220": {"artist": "The Who", "song": "My Generation"},
    "CWS_221": {"artist": "Tom Petty and the Heartbreakers", "song": "Mary Jane's Last Dance"},
    "CWS_222": {"artist": "Weezer", "song": "Say It Ain't So"},
    "CWS_223": {"artist": "Motorhead", "song": "Ace of Spades"},
    "CWS_224": {"artist": "Jimi Hendrix", "song": "Castles Made of Sand"},
    "CWS_225": {"artist": "Jimi Hendrix", "song": "Fire"},
    "CWS_226": {"artist": "Jimi Hendrix", "song": "Foxy Lady"},
    "CWS_227": {"artist": "Jimi Hendrix", "song": "If 6 Was 9"},
    "CWS_228": {"artist": "Jimi Hendrix", "song": "Little Wing"},
    "CWS_229": {"artist": "Jimi Hendrix", "song": "Manic Depression"},
    "CWS_230": {"artist": "Jimi Hendrix", "song": "Purple Haze"},
    "CWS_231": {"artist": "Jimi Hendrix", "song": "The Wind Cries Mary"},
    "CWS_232": {"artist": "Jimi Hendrix", "song": "Red House"},
    "CWS_233": {"artist": "Jimi Hendrix", "song": "Freedom"},
    "CWS_234": {"artist": "Jimi Hendrix", "song": "Voodoo Child (Slight Return)"},
    "CWS_235": {"artist": "Jimi Hendrix", "song": "Bold as Love"}
}


dlc_cws_songs = {
    "CWS_1": ["3 Doors Down", "Kryptonite"],
    "CWS_2": ["3 Doors Down", "Loser"],
    "CWS_3": ["3 Doors Down", "When I’m Gone"],
    "CWS_4": ["Aerosmith", "Dream On"],
    "CWS_5": ["311", "Amber"],
    "CWS_6": ["311", "Beautiful Disaster"],
    "CWS_7": ["311", "Down"],
    "CWS_8": ["Aerosmith", "Legendary Child"],
    "CWS_9": ["Aerosmith", "Oh Yeah"],
    "CWS_10": ["Aerosmith", "Same Old Song And Dance"],
    "CWS_11": ["Aerosmith", "Sweet Emotion"],
    "CWS_12": ["AFI", "Totalimmortal"],
    "CWS_13": ["AFI", "Girl's Not Grey"],
    "CWS_14": ["AFI", "Miss Murder"],
    "CWS_15": ["AFI", "Silver And Cold"],
    "CWS_16": ["Alice in Chains", "Would?"],
    "CWS_17": ["Alice in Chains", "Man in the Box"],
    "CWS_18": ["Alice in Chains", "Hollow"],
    "CWS_19": ["Alice in Chains", "Them Bones"],
    "CWS_20": ["Alice in Chains", "Check My Brain"],
    "CWS_21": ["The Allman Brothers Band", "Jessica"],
    "CWS_22": ["The Allman Brothers Band", "Whipping Post"],
    "CWS_23": ["The Allman Brothers Band", "Southbound"],
    "CWS_24": ["Alter Bridge", "Blackbird"],
    "CWS_25": ["Alter Bridge", "Isolation"],
    "CWS_26": ["Alter Bridge", "Rise Today"],
    "CWS_27": ["Alter Bridge", "Ties That Bind"],
    "CWS_28": ["Avenged Sevenfold", "Beast and the Harlot"],
    "CWS_29": ["Avenged Sevenfold", "Afterlife"],
    "CWS_30": ["Avenged Sevenfold", "Nightmare"],
    "CWS_31": ["B’z", "Juice"],
    "CWS_32": ["B’z", "Giri Giri Chop"],
    "CWS_33": ["B’z", "Easy Come, Easy Go!"],
    "CWS_34": ["The Black Keys", "Just Got to Be"],
    "CWS_35": ["The Black Keys", "Mind Eraser"],
    "CWS_36": ["The Black Keys", "Gold on the Ceiling"],
    "CWS_37": ["Blink-182", "Dammit"],
    "CWS_38": ["Blink-182", "All the Small Things"],
    "CWS_39": ["Blink-182", "What’s My Age Again?"],
    "CWS_40": ["Blondie", "Call Me"],
    "CWS_41": ["Blue Oyster Cult", "Don't Fear The Reaper"],
    "CWS_42": ["Blue Oyster Cult", "Godzilla"],
    "CWS_43": ["Blue Oyster Cult", "Burnin' For You"],
    "CWS_44": ["Bob Dylan", "Just Like a Woman"],
    "CWS_45": ["Bob Dylan", "Like a Rolling Stone"],
    "CWS_46": ["Bob Dylan", "Subterranean Homesick Blues"],
    "CWS_47": ["Cake", "The Distance"],
    "CWS_48": ["Cake", "I Will Survive"],
    "CWS_49": ["Cake", "Never There"],
    "CWS_50": ["Cake", "Short Skirt/Long Jacket"],
    "CWS_51": ["Cake", "Stickshifts and Safety Belts"],
    "CWS_52": ["The Clash", "London Calling"],
    "CWS_53": ["The Clash", "Guns of Brixton"],
    "CWS_54": ["The Clash", "Should I Stay or Should I Go"],
    "CWS_55": ["The Cure", "The End of the World"],
    "CWS_56": ["The Cure", "Just Like Heaven"],
    "CWS_57": ["The Cure", "Lovesong"],
    "CWS_58": ["Disturbed", "Voices"],
    "CWS_59": ["Disturbed", "Down with the Sickness"],
    "CWS_60": ["Disturbed", "Asylum"],
    "CWS_61": ["Fall Out Boy", "America’s Suitehearts"],
    "CWS_62": ["Fall Out Boy", "Dance, Dance"],
    "CWS_63": ["Fall Out Boy", "I Don’t Care"],
    "CWS_64": ["Fall Out Boy", "Sugar, We’re Goin Down"],
    "CWS_65": ["Fall Out Boy", "Thnks fr the Mmrs"],
    "CWS_66": ["Foo Fighters", "Best of You"],
    "CWS_67": ["Foo Fighters", "My Hero"],
    "CWS_68": ["Foo Fighters", "Times Like These"],
    "CWS_69": ["Foo Fighters", "Walk"],
    "CWS_70": ["Foo Fighters", "Wheels"],
    "CWS_71": ["Garbage", "Stupid Girl"],
    "CWS_72": ["Garbage", "I Think I'm Paranoid"],
    "CWS_73": ["Garbage", "Only Happy When it Rains"],
    "CWS_74": ["Green Day", "American Idiot"],
    "CWS_75": ["Green Day", "Basket Case"],
    "CWS_76": ["Green Day", "Oh Love"],
    "CWS_77": ["Hotei", "Battle Without Honor or Humanity"],
    "CWS_78": ["Hotei", "Thrill"],
    "CWS_79": ["Hotei", "Bambina"],
    "CWS_80": ["Incubus", "Wish You Were Here"],
    "CWS_81": ["Incubus", "Love Hurts"],
    "CWS_82": ["Incubus", "Anna Molly"],
    "CWS_83": ["Iron Maiden", "The Number of the Beast"],
    "CWS_84": ["Iron Maiden", "Fear of the Dark"],
    "CWS_85": ["Iron Maiden", "Aces High"],
    "CWS_86": ["Iron Maiden", "2 Minutes to Midnight"],
    "CWS_87": ["Iron Maiden", "Run to the Hills"],
    "CWS_88": ["Judas Priest", "Breaking the Law"],
    "CWS_89": ["Judas Priest", "Living After Midnight"],
    "CWS_90": ["Judas Priest", "Painkiller"],
    "CWS_91": ["Judas Priest", "You’ve Got Another Thing Comin’"],
    "CWS_92": ["Maroon 5", "This Love"],
    "CWS_93": ["Maroon 5", "Misery"],
    "CWS_94": ["Maroon 5", "Harder to Breathe"],
    "CWS_95": ["Mastodon", "Black Tongue"],
    "CWS_96": ["Mastodon", "Colony of Birchmen"],
    "CWS_97": ["Mastodon", "Oblivion"],
    "CWS_98": ["Matchbox Twenty", "Unwell"],
    "CWS_99": ["Matchbox Twenty", "3AM"],
    "CWS_100": ["Matchbox Twenty", "How Far We've Come"],
    "CWS_101": ["Matchbox Twenty", "Push"],
    "CWS_102": ["Matchbox Twenty", "She's So Mean"],
    "CWS_103": ["Megadeth", "Hangar 18"],
    "CWS_104": ["Megadeth", "Public Enemy No. 1"],
    "CWS_105": ["Megadeth", "Symphony of Destruction"],
    "CWS_106": ["Muse", "Hysteria"],
    "CWS_107": ["Muse", "Time is Running Out"],
    "CWS_108": ["Muse", "Supermassive Black Hole"],
    "CWS_109": ["Muse", "Stockholm Syndrome"],
    "CWS_110": ["Muse", "Muscle Museum"],
    "CWS_111": ["My Chemical Romance", "Planetary (GO!)"],
    "CWS_112": ["My Chemical Romance", "Welcome to the Black Parade"],
    "CWS_113": ["My Chemical Romance", "Na Na Na (Na Na Na Na Na Na Na Na Na)"],
    "CWS_114": ["Nickelback", "How You Remind Me"],
    "CWS_115": ["Nickelback", "Rockstar"],
    "CWS_116": ["Nickelback", "Bottoms Up"],
    "CWS_117": ["The Offspring", "Gone Away"],
    "CWS_118": ["The Offspring", "Come Out and Play (Keep ‘Em Separated)"],
    "CWS_119": ["The Offspring", "Self Esteem"],
    "CWS_120": ["Pantera", "Cowboys From Hell"],
    "CWS_121": ["Pantera", "Walk"],
    "CWS_122": ["Pantera", "Domination"],
    "CWS_123": ["Pearl Jam", "Black"],
    "CWS_124": ["Pearl Jam", "Jeremy"],
    "CWS_125": ["Pearl Jam", "Alive"],
    "CWS_126": ["The Police", "Roxanne"],
    "CWS_127": ["The Police", "Message in a Bottle"],
    "CWS_128": ["The Police", "Synchronicity II"],
    "CWS_129": ["Queen", "Keep Yourself Alive"],
    "CWS_131": ["Queen", "Bohemian Rhapsody"],
    "CWS_132": ["Queen", "Fat Bottomed Girls"],
    "CWS_133": ["Queen", "Killer Queen"],
    "CWS_134": ["Queen", "Stone Cold Crazy"],
    "CWS_135": ["Radiohead", "Creep"],
    "CWS_136": ["Radiohead", "Karma Police"],
    "CWS_137": ["Radiohead", "Optimistic"],
    "CWS_138": ["Radiohead", "My Iron Lung"],
    "CWS_139": ["Radiohead", "Just"],
    "CWS_140": ["Rush", "YYZ"],
    "CWS_141": ["Rush", "Tom Sawyer"],
    "CWS_142": ["Rush", "Subdivisions"],
    "CWS_143": ["Rush", "Red Barchetta"],
    "CWS_144": ["Rush", "Limelight"],
    "CWS_145": ["Santana", "Black Magic Woman/Gypsy Queen"],
    "CWS_146": ["Santana", "Oye Como Va"],
    "CWS_147": ["Santana feat. Rob Thomas", "Smooth"],
    "CWS_148": ["The Smashing Pumpkins", "Tonight, Tonight"],
    "CWS_149": ["The Smashing Pumpkins", "Bullet With Butterfly Wings"],
    "CWS_150": ["The Smashing Pumpkins", "Disarm"],
    "CWS_151": ["The Smashing Pumpkins", "Today"],
    "CWS_152": ["The Smashing Pumpkins", "1979"],
    "CWS_153": ["The Smashing Pumpkins", "Cherub Rock"],
    "CWS_154": ["The Strokes", "Reptilia"],
    "CWS_155": ["The Strokes", "Last Nite"],
    "CWS_156": ["The Strokes", "Juicebox"],
    "CWS_157": ["System of a Down", "B.Y.O.B"],
    "CWS_158": ["System of a Down", "Toxicity"],
    "CWS_159": ["System of a Down", "Aerials"],
    "CWS_160": ["Weezer", "Buddy Holly"],
    "CWS_161": ["Weezer", "Hash Pipe"],
    "CWS_162": ["Weezer", "My Name is Jonas"],
    "CWS_163": ["Weezer", "Undone - The Sweater Song"],
    "CWS_164": ["Weezer", "Island in the Sun"],
    "CWS_165": ["The Who", "Baba O’Riley"],
    "CWS_166": ["The Who", "Pinball Wizard"],
    "CWS_167": ["The Who", "Behind Blue Eyes"],
    "CWS_168": ["The Who", "Who are You"]
}

